// Flutter bootstrap script - auto-generated by Flutter
// DO NOT EDIT - This file is generated by Flutter

if (!window._flutter) {
  window._flutter = {};
}
_flutter.loader = null;

(function() {
  'use strict';

  // Load the main.dart.js file
  const script = document.createElement('script');
  script.src = 'main.dart.js';
  script.defer = true;
  document.body.appendChild(script);
})();
